version: "3.1"
services:
  postgres:
    image: postgres:16.1
    container_name: products-api
    environment:
      POSTGRES_DB: products-api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: banco123
    ports:
      - "5432:5432"